const express =require('express')
const mogoose = require('./config/mongoose')
const exphbs = require('express-handlebars')
const Login = require('./models/login')
const bodyParser = require('body-parser') 
const routes = require('./routes')
const app = express()

app.engine('handlebars', exphbs.engine({ defaultLayout: 'main'}))
app.set('view engine', 'handlebars')
app.use(bodyParser.urlencoded({ extended: true })) 
app.use(routes)
app.listen(3000, (req, res)=>{
  console.log('app is on port 3000')
})